name: Daily Cleanup/Report Job

on:
 push:
  workflow_dispatch:

jobs:
  daily-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cleanup script
        run: |
          echo "Running daily cleanup or report"
          # Example: Remove all files in /temp
          rm -f /temp/*
