name: Daily Cleanup my-app/tmp

on:
  push:
    branches: 
    - main
jobs:
  daily-tmp-cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove all files in my-app/tmp
        run: |
            rm -rf ./tmp/*
            echo "Daily cleanup: my-app/tmp files deleteddd."
          
