name: Matrix strategy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "nodejs-matrix.yml"
      - ".github/workflows/nodejs-matrix.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run app
        run: node hello.js
