name: Node.js Matrix CI

on:
workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/totestapproval.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install deps
        run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: manual_approval 
    steps:
      - name: Deploy
        run: echo "Deploying application..."
